# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

# Thymeleaf 配置
  thymeleaf:
    cache: false  # 开发时关闭缓存
    prefix: classpath:/templates/

# Redis 配置（如果使用）
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

upload:
  path: ${user.home}/blog/uploads/avatars/  # 头像存储路径

minio:
  endpoint: http://10.23.46.29:9000
  bucketName: test
  accessKey: minioadmin
  secretKey: minioadmin
